[project]
name = "computational-pwidths"
version = "0.1.0"
description = "Computing p-widths of Riemannian manifolds using persistent homology"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.24.0",
    "scipy>=1.10.0",
    "matplotlib>=3.7.0",
]